// Code generated by the klever-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use klever_sc::proxy_imports::*;

pub struct CertificateRegistryProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for CertificateRegistryProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = CertificateRegistryProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        CertificateRegistryProxyMethods { wrapped_tx: tx }
    }
}

pub struct CertificateRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> CertificateRegistryProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    /// Runs exactly once, when the contract is deployed. 
    ///  
    /// The deployer becomes the contract owner automatically. Here we also 
    /// record the deployer as the first authorized issuer and start IDs at 0. 
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> CertificateRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    /// Called when the contract is upgraded. Kept empty on purpose so an 
    /// upgrade does not reset state. Add migration logic here if you ever 
    /// change the storage layout. 
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> CertificateRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    /// Issue a new certificate for a student. 
    ///  
    /// Only the configured issuer can call this. Returns the new certificate ID 
    /// so the caller (script or frontend) knows what to query next. 
    ///  
    /// > Intermediate focus: this is where you would add expiration or roles. 
    pub fn issue_certificate<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        student: Arg0,
        course: Arg1,
        metadata_uri: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("issueCertificate")
            .argument(&student)
            .argument(&course)
            .argument(&metadata_uri)
            .original_result()
    }

    /// Revoke an existing certificate. Only the issuer can revoke. 
    ///  
    /// Revoking does not delete the record — it flips `revoked = true` so the 
    /// history stays auditable on-chain. 
    pub fn revoke_certificate<
        Arg0: ProxyArg<u64>,
    >(
        self,
        id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("revokeCertificate")
            .argument(&id)
            .original_result()
    }

    /// Transfer the issuer role to a new address. Owner-only for safety. 
    ///  
    /// > Advanced focus: a single issuer is a simplification. The challenges 
    /// > doc walks through turning this into a multi-issuer role system. 
    pub fn set_issuer<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        new_issuer: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setIssuer")
            .argument(&new_issuer)
            .original_result()
    }

    /// Return the full certificate for a given ID, or `None` if it does not exist. 
    pub fn get_certificate<
        Arg0: ProxyArg<u64>,
    >(
        self,
        id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<Certificate<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getCertificate")
            .argument(&id)
            .original_result()
    }

    /// Validate a certificate: returns `true` only if it exists AND is not revoked. 
    ///  
    /// This is the endpoint a verifier (employer, school) would call to check 
    /// whether a certificate is currently valid. 
    pub fn is_valid<
        Arg0: ProxyArg<u64>,
    >(
        self,
        id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("isValid")
            .argument(&id)
            .original_result()
    }

    /// Total number of certificates ever issued (including revoked ones). 
    pub fn get_total_certificates(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTotalCertificates")
            .original_result()
    }

    /// The address allowed to issue and revoke certificates. 
    /// Exposed as a view via `#[view(getIssuer)]`. 
    pub fn issuer(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getIssuer")
            .original_result()
    }
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, Clone, PartialEq, Debug)]
pub struct Certificate<Api>
where
    Api: ManagedTypeApi,
{
    pub id: u64,
    pub student: ManagedAddress<Api>,
    pub course: ManagedBuffer<Api>,
    pub metadata_uri: ManagedBuffer<Api>,
    pub issued_at: u64,
    pub revoked: bool,
}
